name: DangerDetectionSystem
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pytorch-cuda=11.8
  - av
  - opencv
  - torchaudio
  - torchvision
  - notebook
